language: node_js
node_js:
  - "stable"
after_success:
- nyc ./node_modules/.bin/mocha --reporter spec ./backend/test/index.js --reporter spec mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js