language: node_js
node_js:
  - "node"
scripts:
  - npm test
after_success:
- npm run coverage
- npm run test-coverage-report
- istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
Wi
- nyc npm test && nyc report --reporter=text-lcov | coveralls